# Generated by Django 2.1 on 2018-10-14 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='comentary_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.BooleanField()),
                ('comentarys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.comentary')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='compendium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming', models.CharField(max_length=200)),
                ('short', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200)),
                ('containment', models.TextField()),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='compendium_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('compendiums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.compendium')),
                ('correspondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockage', models.BooleanField()),
                ('Fio', models.CharField(max_length=200)),
                ('University', models.CharField(max_length=200)),
                ('Faculty', models.CharField(max_length=200)),
                ('Speciality', models.CharField(max_length=200)),
                ('images_counter', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comentary',
            name='compendiums',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.compendium'),
        ),
        migrations.AddField(
            model_name='comentary',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
