# Generated by Django 2.1 on 2018-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_coment_coment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
